all:
  children:
    wsl:
      hosts:
        localhost:
    windows:
      hosts:
        local_windows:
      vars:
        ansible_host: localhost
        ansible_connection: winrm
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
